version: '3.8'
services:
  ubuntu_2204:
    build: .
    ports:
      - 30022:22
    volumes:
#      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ./workspace:/workspace
    platform: linux/amd64
  ubuntu_2204_1:
    build: .
    ports:
      - 30122:22
    volumes:
#      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ./workspace:/workspace
    platform: linux/amd64

